version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    env_file:
      - .env
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
