name: CI Production
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest

    env:
      HEROKU_APP_URL: ${{ secrets.HEROKU_APP_URL }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install dependencies
        run: npm ci
      - name: Run integration tests
        run: npm test
