name: CI/CD Production
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HEROKU_APP_URL: ${{ secrets.HEROKU_APP_URL }}

    steps:
      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: tldv-video-api
          healthcheck: https://tldv-video-api.herokuapp.com/api/health
          delay: 5
          dontautocreate: true

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install dependencies
        run: npm ci
      - name: Run integration tests
        run: npm test