name: CI/CD Staging
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest

    env:
      HEROKU_APP_URL: ${{ secrets.HEROKU_APP_URL }}

    steps:
      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: ${{secrets.HEROKU_APP_HEALTHCHECK}}
          delay: 5
          dontautocreate: true

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install dependencies
        run: npm ci
      - name: Run integration tests
        run: npm test